-- ===============================
-- Roles & Users
-- ===============================
CREATE TABLE IF NOT EXISTS roles (
                                     id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name  VARCHAR(50) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS users (
                                     id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email    VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    name     VARCHAR(150),
    address  VARCHAR(255),
    enabled  BOOLEAN DEFAULT TRUE
    );

-- Many-to-Many join table tussen users en roles
CREATE TABLE IF NOT EXISTS users_roles (
                                           user_id BIGINT NOT NULL,
                                           role_id BIGINT NOT NULL,
                                           CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id)
    );

-- ===============================
-- Product
-- ===============================
CREATE TABLE IF NOT EXISTS product (
                                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       title         VARCHAR(150) NOT NULL,
    author        VARCHAR(150),
    description   VARCHAR(500),
    price         DECIMAL(12,2) NOT NULL,
    rental_price  DECIMAL(12,2) NOT NULL,
    file_path     VARCHAR(255)
    );

-- ===============================
-- Orders
-- ===============================
CREATE TABLE IF NOT EXISTS orders (
                                      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_id     BIGINT NOT NULL,
                                      created_at  TIMESTAMP NOT NULL,
                                      status      VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    total       DECIMAL(12,2),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id)
    );

-- ===============================
-- Order Items
-- ===============================
CREATE TABLE IF NOT EXISTS order_item (
                                          id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          order_id           BIGINT NOT NULL,
                                          product_id         BIGINT NOT NULL,
                                          type               VARCHAR(10) NOT NULL,          -- "BUY" | "RENT"
    quantity           INT NOT NULL DEFAULT 1,
    price_at_purchase  DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_item_order   FOREIGN KEY (order_id)  REFERENCES orders(id)   ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES product(id)
    );

-- ===============================
-- Rental (1:1 met order_item)
-- ===============================
CREATE TABLE IF NOT EXISTS rental (
                                      id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      order_item_id BIGINT NOT NULL UNIQUE,             -- 1:1 constraint
                                      start_date    TIMESTAMP NOT NULL,
                                      end_date      TIMESTAMP NOT NULL,
                                      CONSTRAINT fk_rental_item FOREIGN KEY (order_item_id) REFERENCES order_item(id) ON DELETE CASCADE
    );

-- ===============================
-- Idempotente migraties / opschoning
-- ===============================


ALTER TABLE product ADD COLUMN IF NOT EXISTS author      VARCHAR(150);
ALTER TABLE product ADD COLUMN IF NOT EXISTS description VARCHAR(500);
ALTER TABLE product ADD COLUMN IF NOT EXISTS file_path   VARCHAR(255);

-- Order status defaults
ALTER TABLE orders ADD COLUMN IF NOT EXISTS status VARCHAR(16) DEFAULT 'PENDING';
UPDATE orders SET status = 'PENDING' WHERE status IS NULL;

-- quantity defaults
ALTER TABLE order_item ADD COLUMN IF NOT EXISTS quantity INT DEFAULT 1;
UPDATE order_item SET quantity = 1 WHERE quantity IS NULL;


ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_role;
ALTER TABLE users DROP COLUMN IF EXISTS role_id;

-- Optionele indices
CREATE INDEX IF NOT EXISTS idx_orders_user_id      ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_order_item_order_id ON order_item(order_id);
CREATE INDEX IF NOT EXISTS idx_order_item_product  ON order_item(product_id);
